config/routes.rb
Rails.application.routes.draw do
  root 'lottery_tickets#index'

  resources :lottery_tickets, only: %i(new create index)
  resources :lottery_draws, only: %i(create show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lottery_draw.rb
class LotteryDraw < ApplicationRecord
  class << self
    def generate_for
      ActiveRecord::Base.transaction do
        lottery_draw = create! numbers: draw_six_numbers
        LotteryTicket.where(lottery_draw: nil).update lottery_draw_id: lottery_draw.id
        lottery_draw
      end
    end

    private

    def draw_six_numbers
      (1..49).to_a.shuffle.take 6
    end
  end
end

app/models/lottery_ticket.rb
class LotteryTicket < ApplicationRecord
  belongs_to :lottery_draw, optional: true

  validate :validate_numbers_in_range, :validate_numbers_are_six

  def validate_numbers_in_range
    if numbers.any? { |number| !number.in? (1..49) }
      errors.add(:numbers, 'Numbers should be between 1 and 49')
    end
  end

  def validate_numbers_are_six
    if numbers.size != 6
      errors.add(:numbers, 'Numbers should be exactly 6')
    end
  end

  class << self
    def not_played_yet
      where lottery_draw: nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lottery_draws_controller.rb
class LotteryDrawsController < ApplicationController
  def create
    lottery_draw = LotteryDraw.generate_for

    redirect_to lottery_draw_path(lottery_draw)
  end

  def show
    @lottery_draw = LotteryDraw.find params[:id]
    @winners = LotteryDrawService.execute @lottery_draw
  end
end

app/controllers/lottery_tickets_controller.rb
class LotteryTicketsController < ApplicationController
  def index
    @lottery_tickets = LotteryTicket.not_played_yet
  end

  def new
    @lottery_ticket = LotteryTicket.new
  end

  def create
    LotteryTicket.create! lottery_ticket_params

    flash[:notice] = 'Ticket created successfully'

    redirect_to lottery_tickets_path
  end

  private

  def lottery_ticket_params
    permitted_params = params.require(:lottery_ticket).permit(:name, :numbers).to_h.with_indifferent_access
    {name: permitted_params[:name], numbers: permitted_params[:numbers].split(',').map(&:strip).map(&:to_i)}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Lottery
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = csp_meta_tag
  body
    .container
      - if flash[:notice]
        javascript:
          toastr.success("#{flash[:notice]}")
      = yield

app/views/lottery_draws/show.html.slim
h1 Winners

p Lottery winning numbers: #{@lottery_draw.numbers.join(',')}

- if @winners.any?
  table.table.table-striped.table-hover
    thead
      tr
        th Name
        th Amount
        th Numbers
    tbody
      - @winners.each do |lottery_ticket|
        tr
          td = lottery_ticket.name
          td = lottery_ticket.amount
          td = lottery_ticket.numbers.join(',')
- else
  p Sorry, no winners in this lottery draw

= link_to 'Create ticket', new_lottery_ticket_path, class: 'btn btn-medium btn-primary'

app/views/lottery_tickets/index.html.slim
h1 Tickets for next lottery run

table.table.table-striped
  thead
    tr
      th Name
      th Numbers
  tbody
    - @lottery_tickets.each do |lottery_ticket|
      tr
        td = lottery_ticket.name
        td = lottery_ticket.numbers.join(',')

div.btn-group
  = link_to 'New Ticket', new_lottery_ticket_path, class: 'btn btn-success'
  = link_to 'Lottery draw', lottery_draws_path, method: :post, class: 'btn btn-primary'

app/views/lottery_tickets/new.html.slim
h1 Create ticket
div.lottery-ticket-js data={numbers: @lottery_ticket.numbers}
  = form_for @lottery_ticket do |form|
    fieldset
      div.form-group
        = form.label :name, class: 'form-label'
        = form.text_field :name, required: true, class: 'form-control'
    fieldset
      legend Please choose 6 numbers
      div.lottery-numbers
      div = form.hidden_field :numbers, required: true, class: 'lottery-numbers-input'
    div.form-group
      = form.submit class: 'btn btn-primary', disabled: true

javascript:
  new window.LotteryView({ el: $('.lottery-ticket-js') })